---
language: en-GB
reviews:
  profile: chill
  review_status: true
  commit_status: true
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  auto_review:
    enabled: true
    labels: ['needs-CR', '!wip']
    drafts: false
  path_filters: ['!dist/', '!**/*.lock', 'frontend/**', 'backend/**']
---
