services:
  - type: web
    name: kyros-dashboard-api
    env: python
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip && pip install poetry \
      && poetry install --no-interaction --no-ansi
    startCommand: poetry run uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: POSTHOG_API_KEY
        sync: false
