name: Bug report
description: Report a reproducible problem
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Be specific and include sample data if possible.
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS, runtime versions, etc.
  - type: textarea
    id: notes
    attributes:
      label: Notes / logs
      description: Paste relevant logs or screenshots.
