"""update_is_active_server_default_to_text

Revision ID: c16925234eb1
Revises: 8b54a15498d5
Create Date: 2025-09-04 13:17:54.247093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c16925234eb1'
down_revision: Union[str, Sequence[str], None] = '8b54a15498d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idempotency_keys', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('job_runs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('job_runs', 'scheduled_job_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('scheduled_jobs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('scheduled_jobs', 'id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('job_runs', 'scheduled_job_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('job_runs', 'id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('idempotency_keys', 'id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
