name: Import CodeRabbit Feedback to Tasks

on:
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

permissions:
  contents: write

jobs:
  import_feedback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Determine PR number
        id: prnum
        run: |
          if [[ "${{ github.event_name }}" == "pull_request_review" ]]; then
            echo "PR=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "pull_request_review_comment" ]]; then
            echo "PR=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "issue_comment" && "${{ github.event.issue.pull_request.url }}" != "" ]]; then
            echo "PR=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          else
            echo "PR=0" >> $GITHUB_OUTPUT
          fi
      - name: Import feedback
        if: steps.prnum.outputs.PR != '0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/import_coderabbit_feedback.py \
            --owner "${{ github.repository_owner }}" \
            --repo "${{ github.event.repository.name }}" \
            --pr "${{ steps.prnum.outputs.PR }}" \
            --assign || true
      - name: Commit tasks updates
        if: steps.prnum.outputs.PR != '0'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(coderabbit): import PR #${{ steps.prnum.outputs.PR }} feedback to tasks'
          file_pattern: |
            collaboration/state/tasks.json
            collaboration/events/events.jsonl
