name: import_coderabbit_on_pr
on: { pull_request: { types: [opened, synchronize, reopened] } }
permissions: { contents: read, pull-requests: write }
jobs:
  import-cr-to-comments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Summarise CodeRabbit review to PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const number = context.payload.pull_request.number;
            const body = "CodeRabbit review imported (no repo writes on PR). Findings will be persisted post-merge via state-sync.";
            await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: number, body });
