name: Update Roadmap

on:
  pull_request:
    types: [closed]
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop' || github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Render roadmap
        run: |
          python scripts/roadmap_tree.py project/roadmap.yml ROADMAP.md
      - name: Commit roadmap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(roadmap): update ROADMAP.md'
          file_pattern: ROADMAP.md
      - name: Post to Discord (optional)
        if: ${{ secrets.DISCORD_WEBHOOK_URL != '' || secrets.DISCORD_PM_WEBHOOK_URL != '' }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_PM_WEBHOOK_URL: ${{ secrets.DISCORD_PM_WEBHOOK_URL }}
          PROJECT_URL: ${{ secrets.PROJECT_URL }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          set -e
          pip install requests
          DASHBOARD_URL="https://$OWNER.github.io/$REPO/"
          # Post to general channel if configured
          if [ -n "${DISCORD_WEBHOOK_URL:-}" ]; then
            python scripts/discord_post.py ROADMAP.md \
              --title "Roadmap Updated" \
              --project-url "${PROJECT_URL:-}" \
              --dashboard-url "$DASHBOARD_URL" \
              --repo-url "https://github.com/$OWNER/$REPO" || true
          fi
          # Post to project management channel if configured
          if [ -n "${DISCORD_PM_WEBHOOK_URL:-}" ]; then
            DISCORD_WEBHOOK_URL="$DISCORD_PM_WEBHOOK_URL" python scripts/discord_post.py ROADMAP.md \
              --title "Roadmap Updated" \
              --project-url "${PROJECT_URL:-}" \
              --dashboard-url "$DASHBOARD_URL" \
              --repo-url "https://github.com/$OWNER/$REPO" || true
          fi
